services:
  - type: web
    name: binance-test
    env: python
    plan: free
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
